'use strict';

module.exports = {
  APPLICATION_SETTINGS_USER_KEY: 'userKey',
  APPLICATION_SETTINGS_IS_CACHE_ENABLED_KEY: 'isCacheEnabledKey',
  APPLICATION_SETTINGS_CACHE_DURATION_KEY: 'cacheDurationKey',
  CACHE_LOCATION_KEY: 'locationKey',
  DEFAULT_CACHE_DURATION: 5 * 60,
  ALL_TOURIST_SITES_TYPE: 0,
  OFFICIAL_TOURIST_SITES_TYPE: 1,
  UNOFFICIAL_TOURIST_SITES_TYPE: 2,
};